/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiN8nWorkflowsRouteImport } from './routes/api/n8n.workflows'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai.generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nWorkflowsRoute = ApiN8nWorkflowsRouteImport.update({
  id: '/api/n8n/workflows',
  path: '/api/n8n/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai/generate' | '/api/n8n/workflows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai/generate' | '/api/n8n/workflows'
  id: '__root__' | '/' | '/api/ai/generate' | '/api/n8n/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiN8nWorkflowsRoute: typeof ApiN8nWorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/workflows': {
      id: '/api/n8n/workflows'
      path: '/api/n8n/workflows'
      fullPath: '/api/n8n/workflows'
      preLoaderRoute: typeof ApiN8nWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiN8nWorkflowsRoute: ApiN8nWorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
