/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiRunsRouteImport } from './routes/ai-runs'
import { Route as AiConsoleRouteImport } from './routes/ai-console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiN8nWorkflowsRouteImport } from './routes/api/n8n.workflows'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai.generate'

const AiRunsRoute = AiRunsRouteImport.update({
  id: '/ai-runs',
  path: '/ai-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConsoleRoute = AiConsoleRouteImport.update({
  id: '/ai-console',
  path: '/ai-console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nWorkflowsRoute = ApiN8nWorkflowsRouteImport.update({
  id: '/api/n8n/workflows',
  path: '/api/n8n/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-console': typeof AiConsoleRoute
  '/ai-runs': typeof AiRunsRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-console': typeof AiConsoleRoute
  '/ai-runs': typeof AiRunsRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-console': typeof AiConsoleRoute
  '/ai-runs': typeof AiRunsRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/n8n/workflows': typeof ApiN8nWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-console'
    | '/ai-runs'
    | '/api/ai/generate'
    | '/api/n8n/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-console'
    | '/ai-runs'
    | '/api/ai/generate'
    | '/api/n8n/workflows'
  id:
    | '__root__'
    | '/'
    | '/ai-console'
    | '/ai-runs'
    | '/api/ai/generate'
    | '/api/n8n/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConsoleRoute: typeof AiConsoleRoute
  AiRunsRoute: typeof AiRunsRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiN8nWorkflowsRoute: typeof ApiN8nWorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-runs': {
      id: '/ai-runs'
      path: '/ai-runs'
      fullPath: '/ai-runs'
      preLoaderRoute: typeof AiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-console': {
      id: '/ai-console'
      path: '/ai-console'
      fullPath: '/ai-console'
      preLoaderRoute: typeof AiConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/workflows': {
      id: '/api/n8n/workflows'
      path: '/api/n8n/workflows'
      fullPath: '/api/n8n/workflows'
      preLoaderRoute: typeof ApiN8nWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConsoleRoute: AiConsoleRoute,
  AiRunsRoute: AiRunsRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiN8nWorkflowsRoute: ApiN8nWorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
